# Generated by Django 5.2.1 on 2025-05-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signer', '0002_keypair_signeddocument_delete_signedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signeddocument',
            name='key_pair',
        ),
        migrations.RemoveField(
            model_name='signeddocument',
            name='user',
        ),
        migrations.DeleteModel(
            name='KeyPair',
        ),
        migrations.DeleteModel(
            name='SignedDocument',
        ),
    ]
